import {URI,PORT,TOKEN_SECRET,ACCOUNT_SID,TWILIO_PHONE_NUMBER,TWILIO_AUTH_TOKEN,TWILIO_PHONE_NUMBER_TO,EMAILPaSS,EMAIL,ADMINEMAIL} from "./server_Config.js";
import connectDB from "./db_config.js";

export {connectDB, URI,PORT,TOKEN_SECRET,ACCOUNT_SID,TWILIO_PHONE_NUMBER,TWILIO_AUTH_TOKEN,TWILIO_PHONE_NUMBER_TO,EMAILPaSS,EMAIL,ADMINEMAIL};
